api_platform:
    title: GRAMC-API
    version: 2.0.0
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        formats: jsonld
        pagination_enabled: false
        security: "is_granted('ROLE_API')"
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    eager_loading:
        max_joins: 1000
    formats:
        jsonld: [ 'application/ld+json' ]
        jsonapi: [ 'application/vnd.api+json' ]
        json: [ 'application/json' ]
        xml: [ 'application/xml', 'text/xml' ]
        csv: [ 'text/csv' ]
        html: [ 'text/html' ]