framework:
    notifier:
        chatter_transports:
        texter_transports:
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email','browser']
            high: ['email','browser']
            medium: ['browser']
            low: ['browser']
        admin_recipients:
            - { email: admin@example.com }
