twig:
    paths:
       'templates': ~
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
       infos: '@App\GramcServices\ServiceInfos'
       serviceVersions: '@App\GramcServices\ServiceVersions'
       serviceRallonges: '@App\GramcServices\ServiceRallonges'
       serviceProjets: '@App\GramcServices\ServiceProjets'
       serviceUsers: '@App\GramcServices\ServiceUsers'
       serviceServeurs: '@App\GramcServices\ServiceServeurs'
       serviceRessources: '@App\GramcServices\ServiceRessources'
       serviceDacs: '@App\GramcServices\ServiceDacs'
       mailadmin: '%mailadmin%'
       mailsupport: '%mailsupport%'
       mesoc: '%mesoc%'
       mesoc_web: '%mesoc_web%'
       mesoc_attrib: '%mesoc_attrib%'
       mesoc_merci: '%mesoc_merci%'
       mesoc_cgu: '%mesoc_cgu%'
       mesoc_visu: '%mesoc_visu%'
       mesoc_formation: '%mesoc_formation%'
       mesoc_address: '%mesoc_address%'
       conso_seuil_1: '%conso_seuil_1%'
       conso_seuil_2: '%conso_seuil_2%'
       prj_prefix: '%prj_prefix%'
       max_page_nb: '%max_page_nb%'
       max_size_doc: '%max_size_doc%'
       rapport_dactivite: '%rapport_dactivite%'
       fichier_attache: '%fichier_attache%'
       resp_peut_modif_collabs: '%resp_peut_modif_collabs%'
       clessh_algos: '%clessh_algos%'
       mode_auth: '%mode_auth%'
