controllers:
    resource: ../../src/Controller/
    type: attribute

# Suppression de la partie altermeso
#controllers2:
#    resource: ../../altermeso/src/Controller/
#    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: attribute
