<?php

/**
 * This file is part of GRAMC (Computing Ressource Granting Software)
 * GRAMC stands for : Gestion des Ressources et de leurs Attributions pour Mésocentre de Calcul
 *
 * GRAMC is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 *  GRAMC is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with GRAMC.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  authors : Miloslav Grundmann - C.N.R.S. - UMS 3667 - CALMIP
 *            Emmanuel Courcelle - C.N.R.S. - UMS 3667 - CALMIP
 *            Nicolas Renon - Université Paul Sabatier - CALMIP
 **/

namespace App\Repository;

/**
 * LaboratoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaboratoireRepository extends \Doctrine\ORM\EntityRepository
{
    function findAllSorted()
    {
        $dql = 'SELECT l FROM App:Laboratoire l ORDER BY l.numeroLabo,l.acroLabo';
        $query = $this->getEntityManager()->createQuery($dql);
        return $query->getResult();
    }

    /**************************
     * 
     * Renvoie tous les laboratoires pour lesquels on  au moins un user demandant un login sur un serveur géré par $admname
     *
     **************/ 
    function findByAdmname(string $admname)
    {
        $dql = 'SELECT l FROM App:Laboratoire l, App:User u, App:Serveur s, App:Individu i WHERE u.loginname IS NOT NULL AND u.serveur = s AND u.individu = i AND l.idLabo = i.labo AND s.admname = :admname';
        $query = $this->getEntityManager()->createQuery($dql);
        return $query->setParameter('admname', $admname )->getResult();
                 
        /*select distinct l.acro_labo, a.adresse from user as u, serveur as s, laboratoire as l, individu as i, adresseip as a,
        collaborateurVersion as cv  where u.loginname is not null and u.id_serveur=s.nom and u.id_individu=i.id_individu
        and l.id_labo=i.id_labo and l.id_labo=a.id_labo and s.admname="apiuft" order by l.acro_labo;*/
    }
}
