---

# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
# https://symfony.com/doc/current/service_container/import.html
imports:
        - { resource: parameters.yaml }

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    #    service_name:
    #        class: App\Directory\ClassName
    #        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
     
    # Tous les controleurs sont des services, ils peuvent utiliser la dependency injection
    #altermeso_controllers:
    #    namespace: App\Controller\
    #    resource: '../altermeso/src/Controller/*'
    #    tags: [controller.service_arguments]

    app_controllers:
        namespace: App\Controller\
        #public: true
        resource: '../src/Controller/*'
        tags: [controller.service_arguments]

    # Repositories:
    #App\Repository\:
    #    resource: '../src/Repository/*Repository.php'
    #    tags: [doctrine.repository_service]

    # La plupart des services gramc sont dans le répertoire GramcServices
    App\GramcServices\:
        resource: '../src/GramcServices/*'
        exclude: '../src/GramcServices/Workflow/*'

    # Workflows
    # Seuls certains objets définis dans le répertoire Workflows sont des services
    App\GramcServices\Workflow\:
        resource: '../src/GramcServices/Workflow/*/*Workflow.php'

    # Securité
    App\Security\:
        resource: '../src/Security/*'
    
    App\EventListener\ExceptionListener:
        arguments: ["%kernel.debug%"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    # Evenements Doctrine lorsqu'on met à jour une version
    App\EventListener\VersionStamp:
        tags:
            - # these are the options required to define the entity listener
                name: 'doctrine.orm.entity_listener'
                event: 'preUpdate'
                entity: 'App\Entity\Version'

    App\EventListener\ProjetDerniereVersion:
        tags:
            - # these are the options required to define the entity listener
                name: 'doctrine.orm.entity_listener'
                event: 'postPersist'
                entity: 'App\Entity\Version'
            -   name: 'doctrine.orm.entity_listener'
                event: 'postRemove'
                entity: 'App\Entity\Version'
            -   name: 'doctrine.orm.entity_listener'
                event: 'postUpdate'
                entity: 'App\Entity\Version'

    # SERVICES GRAMC
    App\GramcServices\DonneesFacturation:
        arguments: ['%dfct_directory%']

    App\GramcServices\ServiceProjets:
        arguments: ["%prj_prefix%",
                    "%signature_directory%",
                    "%rapport_directory%",
                    "%fig_directory%",
                    "%dfct_directory%"]

    App\GramcServices\ServiceVersions:
        arguments: ["%prj_prefix%",
                    "%rapport_directory%",
                    "%fig_directory%",
                    "%signature_directory%",
                    "%max_fig_width%",
                    "%max_fig_height%",
                    "%max_size_doc%",
                    "%resp_peut_modif_collabs%" ]
        
    App\GramcServices\ServiceMenus:
        arguments: [ "%max_rall%" ]
        
    App\GramcServices\ServiceNotifications:
        arguments: [ "%mailfrom%","%noedition_expertise%" ]

    App\GramcServices\ServiceExperts\ServiceExperts:
        arguments: [ "%max_expertises_nb%" ]

    App\GramcServices\ServiceExperts\ServiceExpertsRallonge:
        arguments: [ "%max_expertises_nb%" ]

    App\GramcServices\ServiceInvitations:
        arguments: [ "%invit_duree%" ]

    App\GramcServices\Cron\GramcCronTask\TempsCronTask:
        arguments: [ "%dyn_duree_post%"]

    App\GramcServices\Cron\GramcCronTask\TempsStdbyCronTask:
        arguments: [ "%dyn_duree_post%"]

    App\Controller\VersionSpecController:
        arguments: [ "%dyn_duree%", "%dyn_duree_post%" ]
        
    App\Controller\ExpertiseController:
        arguments: [ "%dyn_duree%","%max_expertises_nb%" ]

    # Formulaires, validateurs, securité
    App\Form\:
        resource: '../src/Form/*'
        exclude: '../src/Form/IndividuForm/*'
        tags: ["form.type"]

    App\Validator\Constraints\PagesNumberValidator:
        arguments: [ "%max_page_nb%" ]
        tags: ["validator.constraint_validator" ]

    App\Validator\Constraints\ClesshValidator:
        arguments: [ "%clessh_algos%" ]
        tags: ["validator.constraint_validator" ]

    App\Security\GramcAuthenticator:
        arguments:
            $knl_debug: '%kernel.debug%'
            $mode_auth: '%mode_auth%'
    
    # Commandes
    app.gramc.sendamail:
        class: App\Command\Sendamail
        #arguments: ["@twig","@app.gramc.ServiceNotifications"]
        arguments: ["%kernel.environment%"]
        tags: ["console.command"]
    App\Command\Sendamail: '@app.gramc.sendamail'

    App\Command\Rgpd:
        tags: ["console.command"]

    App\Command\NettCompta:
        tags: ["console.command"]

    App\Command\AddCompta:
        arguments: ["%kernel.debug%"]
        tags: ["console.command"]

    App\Command\Brouillage:
        arguments: ["%kernel.debug%"]
        tags: ["console.command"]

    App\Command\KeepOnly:
        arguments: ["%kernel.debug%"]
        tags: ["console.command"]

    App\Command\InitLimitDate:
        arguments: [ "%dyn_duree%" ]
        tags: ["console.command"]

    App\Command\InitRessources:
        tags: ["console.command"]
