<?php  //[STAMP] bf617dbca3efd32f7d20b75da42129bf
// phpcs:ignoreFile
namespace App\Tests\Support\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build

trait ApplicationTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
